name: Manual test execution.

on:
  workflow_dispatch:
    inputs:
      testInput:
        description: 'Test input'     
        required: true
        default: 'ENV Variables test'
    

jobs:
  test:
    name: Manual text execution.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Workflow input
        run: |
          echo "Test Input: $TEST_INPUT"
        env:
          TEST_INPUT: ${{ github.event.inputs.testInput }}
